### ISSUE TITLE
Wireframe glitch

### ISSUE THREAD

**Issue by rdecapomaranca** [gjbekker/molmil#4]
When selecting a wireframe style for the whole structure and then selecting BallStick style for molecules that are not sequential aka. chains[0].molecules[1] and chains[0].molecules[7] a line appears connecting the two molecules in some point. Below is an image of such example produced on the demo site for labelling functionality.
![wireframe_lines](https://cloud.githubusercontent.com/assets/7722193/19593039/d7551a24-977e-11e6-80a2-850bbf6a27cf.png)
This glitch appears in combination of styles:

structure | molecules
------------------------------
wireframe | BallStick
wireframe | stick
BallStick | wireframe
stick | wireframe
wireframe | CaTrace

**Comment by gjbekker** [comment]
Thank you for the detailed bug report. 

I have made a correction to the code in order to correctly render the wireframe structure with intermittent alternative render modes. 

BTW, you also mentioned wireframe structure and a CaTrace molecule (your last item). I don't think such a combination is possible, at least not via the user interface. Did you mean the other way around?

**Comment by rdecapomaranca** [comment]
I don't use user interface, I use code (rendering trough javascript with canvas.molmilViewer). It works now (all combinations), so thank you very much.
